settings:
  giveDelay: 1

item:
  name: "&bCosmetics"
  material: BEACON
  data: 0
  slot: 4
  amount: 1
  description:
    - "&7Right click to select a cosmetic!"

messages:
  no_cosmetics: "&cYou do not have permission to use cosmetics, donate for them at &c&lpeko.cc/store&c."
  no_permission: "&cYou do not have permission to use this cosmetic."
  selected_cosmetic: "&eYou have selected the &f%displayName% &ecosmetic."
  unselected_cosmetic: "&eYou have unselected the &f%displayName% &ecosmetic."